apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:         
  rhtap/gitops: d1j8bkemp-go 
  janus-idp.io/tekton: d1j8bkemp-go
  backstage.io/kubernetes-id: d1j8bkemp-go
  backstage.io/kubernetes-namespace: rhtap-app 
  app.kubernetes.io/part-of: d1j8bkemp-go
resources:
  - ci-tekton.yaml
  - application-dev.yaml
  - application-stage.yaml
  - application-prod.yaml